language: objective-c
rvm:
- 2.2.0
osx_image: xcode7.3
env:
  global:
  - APP_NAME="PLLivingDemo"
git:
  submodules: false
before_install:
- git submodule update --init --recursive
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
before_script:
- xctool clean -workspace $APP_NAME.xcworkspace -scheme $APP_NAME
script:
- xctool -workspace $APP_NAME.xcworkspace -scheme $APP_NAME -sdk iphoneos -configuration Debug OBJROOT=$PWD/build SYMROOT=$PWD/build